<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>ADICIONAR Casas</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    </head>
    <body>
        <h1>ADICIONAR CASAS</h1>

        <form method="POST">
            Endereço: <br>
            <input type="text" name="Endereco"><br>
            Bairro: <br>
            <input type="text" name="Bairro"><br>
            CEP: <br>
            <input type="text" name="Cep"><br><br>
            Cidade: <br>
            <input type="text" name="Cidade"><br><br>

            <input type="submit" value="Cadastrar">
        </form>
    </body>
</html>
