<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Lista de Casas Disponiveis</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    </head>
    <header>
        <div class="cabecalho">Informações importantes</div>
    </header>
    <body>
        <h1>Casas</h1>
        <ul>
            <?php foreach ($lista as $item): ?>
            <li> 
                <?php echo $item['Endereco']; ?> - <?php echo $item['Bairro'];?> - CPF: <?php echo $item['Cep']; ?> - <?php echo $item['Cidade'];?>
                <a href="./edit/<?php echo $item['Nome'];?>">Editar</a> 
                <a href="./del/<?php echo $item['Nome'];?>">Excluir</a> 
            </li>
            <?php endforeach; ?>
        </ul>

        <a href="./adicionarContato">Adicionar Contato</a>
    </body>
</html>
